---
version: '3'

services:
  db:
    restart: always
    image: mysql:5.7
    volumes:
      - ./src/server/scripts/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=vault
      - MYSQL_DATABASE=vault

  server:
    restart: always
    build:
      context: .
      args:
        db_host: db
        db_port: 3306
        db_name: vault
        db_user: root
        db_pass: vault
    ports:
      - "${PORT}:80"
    depends_on:
      - db
