pipeline {
    agent {
        docker {
            image 'docker.internal.kevinlin.info/infra/ci-base:0.1.0'
            label 'docker-executor'
        }
    }

    stages {
        stage('Install') {
            steps {
                sh 'npm-s3 install'
            }
        }
        stage('Test') {
            parallel {
                stage('Build') {
                    environment {
                        NODE_ENV = 'production'
                    }
                    steps {
                        sh 'npm run build'
                    }
                }
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Unit') {
                    steps {
                        sh 'npm run test'
                    }
                }
            }
        }
    }
}
